# Generated by Django 5.2.3 on 2025-06-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sprint4_new_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auto_sync_enabled',
        ),
        migrations.AddField(
            model_name='account',
            name='is_plaid_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='last_plaid_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='auto_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='plaid_institution_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sync_frequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_plaid_transaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='report_email_frequency',
            field=models.CharField(choices=[('never', 'Never'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20),
        ),
    ]
